#' Example pretest-posttest dataset for the IVC diagnostic
#'
#' A simulated dataset generated by [ivc_simulate()] with `n = 1000`,
#' `gamma = 1` (strong instrument), `kappa = 0.2` (mild exogeneity violation),
#' and true effect `tau = 0.5`. Useful for examples and tests.
#'
#' @format A data frame with 1000 rows and 4 variables:
#' \describe{
#'   \item{Z}{Candidate instrument.}
#'   \item{A}{Treatment.}
#'   \item{P}{Pretest.}
#'   \item{Y}{Posttest outcome.}
#' }
#' @usage data(ivc_example)
"ivc_example"
